service: microservice-notification

frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-1
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  profile: pdp-auction
  iam:
   role:
    statements:
      - Effect: 'Allow'
        Action:
         - ses:SendEmail
        Resource: arn:aws:ses:*
      - Effect: Allow
        Action:
         - sqs:ReceiveMessage
        Resource: ${self:custom.mailQueue.arn}

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
  
functions:
  sendEmail:
    handler: src/handlers/sendEmail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1          

resources:
  Resources:
   MailQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.mailQueue.name}
  Outputs:
   MailQueueArn:
     Value: ${self:custom.mailQueue.arn}
     Export:
       Name: ${self:custom.mailQueue.name}-Arn
   MailQueueUrl:
     Value: ${self:custom.mailQueue.url}
     Export:
       Name: ${self:custom.mailQueue.name}-Url
